---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: buildkite-agent-postgres
  annotations:
    a8r.io/description: "Properties for postgres connection"
stringData:

  PGUSER: buildkitepg
  PGPASSWORD: ...
  PGHOST: ha-postgres
  PGPORT: "5432"
  PGDATABASE: ticketdb