---
apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko
  labels:
    app: kaniko
  annotations:
    a8r.io/description: "Image builder job with kaniko"
spec:

  parallelism: 1
  completions: 1
  backoffLimit: 1
  activeDeadlineSeconds: 300

  manualSelector: true
  selector:
    matchLabels:
      app: kaniko

  template:
    metadata:
      labels:
        app: kaniko
    spec:
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--dockerfile=Dockerfile"
            - "--context=${CONTEXT}"
            - "--destination=${DESTINATION}"
            # needed proxy settings as build vars
            - "--build-arg=HTTP_PROXY=${HTTP_PROXY}"
            - "--build-arg=HTTPS_PROXY=${HTTPS_PROXY}"
            - "--build-arg=NO_PROXY=${NO_PROXY}"
          envFrom:
            - secretRef:
                name: proxy
          volumeMounts:
            - name: docker-config
              mountPath: /kaniko/.docker/
          resources:
            limits:
              cpu: 1
              memory: 516Mi
            requests:
              cpu: 1
              memory: 516Mi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: false
      serviceAccountName: kaniko
      restartPolicy: Never
      volumes:
        - name: docker-config
          configMap:
            name: docker-config