---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: IfNotPresent
      args:
        - "--dockerfile=Dockerfile"
        - "--context=${CONTEXT}"
        - "--destination=${DESTINATION}"
      envFrom:
        - secretRef:
            name: proxy
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      resources:
        limits:
          cpu: 1
          memory: 516Mi
        requests:
          cpu: 1
          memory: 516Mi
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        privileged: false
  serviceAccountName: kaniko
  restartPolicy: Never
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
