#!/bin/bash

set -eou pipefail

if [[ ! -x $(which psql) ]]; then
    echo "Command psql not installed" 1>&2
    exit 1
fi

if [[ ! $(pg_isready) ]]; then
    echo "Connection to server failed" 1>&2
    exit 1
fi

# superuser
SUPERUSER=(PGUSER="${POSTGRES_USER}" PGPASSWORD="${POSTGRES_PASSWORD}")
pgenv="env ${SUPERUSER[*]}"

#
# Initiate database
#
function init {

    exists=$($pgenv PGDATABASE= psql -tAc "SELECT 1 FROM pg_database WHERE datname='$PGDATABASE';")
    if [[ -n $exists ]]; then
      echo "Database already initialized"
      exit 0
    fi

    $pgenv PGDATABASE= psql -qc "CREATE DATABASE \"$PGDATABASE\" WITH OWNER \"$PGUSER\";"
    $pgenv psql -qc "
      CREATE USER \"$PGUSER\" WITH
        NOSUPERUSER NOCREATEDB NOCREATEROLE
        ENCRYPTED PASSWORD '$PGPASSWORD'
      ;" 2> /dev/null || true
    $pgenv psql -qc "GRANT ALL PRIVILEGES ON DATABASE \"$PGDATABASE\" TO \"$PGUSER\";"
    $pgenv psql -qc "REVOKE connect ON DATABASE \"$PGDATABASE\" FROM PUBLIC;"
    psql -qc "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
    psql -qc "
      CREATE TABLE IF NOT EXISTS tokens (
        email               VARCHAR(50) PRIMARY KEY,
        bitbucket_user      VARCHAR(50) UNIQUE,
        bitbucket_token     VARCHAR,
        registry_user       VARCHAR(50) UNIQUE,
        registry_token      VARCHAR
      );
    "
    psql -qc "
      CREATE OR REPLACE FUNCTION hash_update_tg()
      RETURNS trigger AS \$\$
        BEGIN
          IF (TG_OP = 'INSERT') OR (TG_OP = 'UPDATE') THEN
            IF OLD.bitbucket_token IS NULL OR NEW.bitbucket_token != OLD.bitbucket_token THEN
              NEW.bitbucket_token = PGP_SYM_ENCRYPT(NEW.bitbucket_token, '$AES256_KEY');
            END IF;
            IF OLD.registry_token IS NULL OR NEW.registry_token != OLD.registry_token THEN
              NEW.registry_token = PGP_SYM_ENCRYPT(NEW.registry_token, '$AES256_KEY');
            END IF;
            RETURN NEW;
          END IF;
        END;
      \$\$ LANGUAGE plpgsql;
    "
    psql -qc "
      CREATE TRIGGER secret_tokens_insert_update
      BEFORE INSERT OR UPDATE ON tokens
      FOR EACH ROW EXECUTE PROCEDURE hash_update_tg();
    " 2> /dev/null || true

    echo "Database initialized"
}

#
# Load user tokens to env
#
function setenv {
  EMAIL=$1

  # ensure user exists
  if [[ -z "$(psql -tc "SELECT 1 FROM tokens WHERE email = '$EMAIL';")" ]]; then
    echo "User '$EMAIL' does not exist"
    exit 1
  fi

  readarray -t select <<< "$(psql -F "," -Ac "
    SELECT email,
      bitbucket_user,
      PGP_SYM_DECRYPT(bitbucket_token::bytea, '$AES256_KEY') AS bitbucket_token,
      registry_user,
      PGP_SYM_DECRYPT(registry_token::bytea, '$AES256_KEY') AS registry_token
    FROM tokens WHERE email = '$EMAIL';
  " | head -2)"

  # export secrets as environment variables
  IFS="," read -ra headers <<< "${select[0]}"
  IFS="," read -ra row <<< "${select[1]}"
  for i in "${!headers[@]}"; do export "$(echo "${headers[$i]}" | tr "[:lower:]" "[:upper:]")"="${row[$i]:-}"; done
}

#
# Manual
#
function help {
    echo "Usage: $(basename "$0") command"
    echo "Commands: init"
}

# input function
option=$1

shift 1

if [[ -z $option ]]; then
    help
    exit 1
fi

case $option in
    init)
        init
        ;;
    setenv)
        setenv "$@"
        ;;
    *)
        help
        ;;
esac
