---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite-agent
spec:
  template:
    spec:
      containers:
        - name: buildkite
          args:
            - start
            - --name=%hostname
            - --tags=env=prd
            - --tags=namespace=services
            - --tags=kubernetes=true
            - --tags=kaniko=true