---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kaniko
  annotations:
    kubernetes.io/description: 'psp for kaniko builds'
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false

  allowedCapabilities:
    - CHOWN
  requiredDropCapabilities: [ ]
  defaultAddCapabilities: [ ]

  hostNetwork: false
  hostIPC: false
  hostPID: false

  seLinux: # harness for SELinux
    rule: RunAsAny

  runAsUser:
    rule: RunAsAny
  runAsGroup:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - configMap
    - secret
    - emptyDir
    - persistentVolumeClaim
  readOnlyRootFilesystem: false