#!/usr/bin/env bash

# Hook that runs before th checkout hook.
# This hook is meant to replace git protocol with https
# since port 22 - used for ssh - might be blocked.

set -euo pipefail

if [[ ! -v ${BITBUCKET_USER} ]] || [[ ! -v ${BITBUCKET_TOKEN} ]]; then
  echo "Missing credentials for user '$BUILDKITE_BUILD_CREATOR_EMAIL'"
  exit 1
fi

# change protocol git to https
BUILDKITE_REPO=$(sed "s/:/\//; s/git@/https:\/\/${BITBUCKET_USER}:${BITBUCKET_TOKEN}@/" <<< "$BUILDKITE_REPO")
