---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services-dev

resources:
  - ../../base/
  - namespaces/buildkite-agent/

components:
  - ../../components/buildkite-agent/unprivileged/
  - ../../components/kaniko/