---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-services

resources:
  - ../../buildkite-agent/base/

components:
  - ../../components/buildkite-agent/unprivileged/
  - ../../components/buildkite-agent/privileged/