---
apiVersion: v1
kind: Namespace
metadata:
  name: services
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: proxy
  namespace: services
stringData:
  HTTP_PROXY: ...
  HTTPS_PROXY: ...
  NO_PROXY: ...