---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildkite-agent

resources:
  - ../../../../../base/.secrets/

components:
  - ../../../../../components/buildkite-agent/privileged/.secrets/