---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: buildkite-agent

resources:
  - ../../../../../base/.proxy.yaml
  - ../../../../../base/.secrets.yaml

patchesStrategicMerge:
  - ../../../../../components/buildkite-agent/privileged/.secrets.yaml