---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pgpvc
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: standard
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
  annotations:
    a8r.io/description: "PostgreSQL database for buildkite agent"

spec:
  replicas: 1

  serviceName: postgres
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: docker-config
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: proxy
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 516Mi
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      serviceAccountName: buildkite-agent
      terminationGracePeriodSeconds: 900
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgpvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgres
  type: NodePort