---
steps:
  - label: ":docker: :kubernetes: Build image with kaniko"
    command: ".buildkite/steps/kaniko/kaniko.sh"
    agents:
      env: prd
      namespace: services
      kubernetes: true
      kaniko: true