---
steps:
  - label: ":docker: :kubernetes: Build image with kaniko"
    command: ".buildkite/steps/kaniko/kaniko.sh"
    agents:
      env: kubernetes
      namespace: buildkite-agent
      privileged: true
      kaniko: true