---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: buildkite-agent
rules:
  - apiGroups: [ policy ]
    resources: [ podsecuritypolicies ]
    verbs: [ use ]
    resourceNames: [ buildkite-agent ]
  - apiGroups: [ "" ]
    resources: [ pods, pods/log, replicasets, statefulsets, configmaps, secrets ]
    verbs: [ create, get, list, update, delete, patch, watch ]
  - apiGroups: [ apps, batch, extensions ]
    resources: [ deployments, jobs ]
    verbs: [ create, get, list, update, delete, patch, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: buildkite-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: buildkite-agent
subjects:
  - kind: ServiceAccount
    name: buildkite-agent